logsBucket: 'gs://caring-465016-cloud-build-logs'
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-app/my-app:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-app/my-app:latest']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
    - run
    - deploy
    - my-app
    - --image=us-central1-docker.pkg.dev/$PROJECT_ID/my-app/my-app:latest
    - --region=us-central1
    - --platform=managed
    - --allow-unauthenticated
    - --set-env-vars=PORT=8081
  entrypoint: gcloud
