steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-app:latest', '.']
  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-app:latest']
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - run
      - deploy
      - my-app
      - --image=gcr.io/$PROJECT_ID/my-app:latest
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated
      - --set-env-vars=PORT=8081
    entrypoint: gcloud
options:
  logging: CLOUD_LOGGING_ONLY
