steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/botttt-465007/my-app:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/botttt-465007/my-app:latest']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'my-app', 
           '--image', 'gcr.io/botttt-465007/my-app:latest', 
           '--region', 'us-central1',  # Changed to us-central1
           '--platform', 'managed',
           '--allow-unauthenticated']
options:
  logging: CLOUD_LOGGING_ONLY
