logsBucket: 'gs://caring-465016-cloud-build-logs'
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/matters-465204/my-app/my-app:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/matters-465204/my-app/my-app:latest']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
    - run
    - deploy
    - my-app
    - --image=us-central1-docker.pkg.dev/matters-465204/my-app/my-app:latest
    - --region=us-central1
    - --platform=managed
    - --allow-unauthenticated
    - --set-env-vars=PORT=8080
    - --set-secrets=BOT_TOKEN=bot-token:latest,CHAT_ID=chat-id:latest,REDIS_HOST=redis-host:latest,REDIS_PORT=redis-port:latest,REDIS_PASSWORD=redis-password:latest,GCS_BUCKET_NAME=gcs-bucket-name:latest
  entrypoint: gcloud
